version: '2.7'

services:

  admin-api:
    build:
      context: './admin'
    ports:
      - '3001:3001'
    volumes:
      - './admin:/admin/app'

  frontend:
    build:
      context: './booking'
    ports:
      - '3002:3002'
    volumes:
      - './booking:/booking/app'